# Generated by Django 6.1 on 2026-09-20 14:27

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_convert_richtext_to_streamfield_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citylandingpage',
            name='about',
            field=wagtail.fields.StreamField([('rich_text', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
        migrations.AlterField(
            model_name='citylandingpage',
            name='intro',
            field=wagtail.fields.StreamField([('rich_text', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
        migrations.AlterField(
            model_name='seolandingpage',
            name='bottom_section_1_content',
            field=wagtail.fields.StreamField([('rich_text', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
        migrations.AlterField(
            model_name='seolandingpage',
            name='bottom_section_2_content',
            field=wagtail.fields.StreamField([('rich_text', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
        migrations.AlterField(
            model_name='seolandingpage',
            name='bottom_section_3_content',
            field=wagtail.fields.StreamField([('rich_text', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
        migrations.AlterField(
            model_name='seolandingpage',
            name='final_thoughts_content',
            field=wagtail.fields.StreamField([('rich_text', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
        migrations.AlterField(
            model_name='seolandingpage',
            name='hero_left_text',
            field=wagtail.fields.StreamField([('rich_text', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}, help_text='Content shown on left side of hero'),
        ),
        migrations.AlterField(
            model_name='seolandingpage',
            name='intro_text',
            field=wagtail.fields.StreamField([('rich_text', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
        migrations.AlterField(
            model_name='seolandingpage',
            name='listing_section_title',
            field=models.CharField(default='Top Rehabs', max_length=255),
        ),
        migrations.AlterField(
            model_name='seolandingpage',
            name='section_1_content',
            field=wagtail.fields.StreamField([('rich_text', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
        migrations.AlterField(
            model_name='seolandingpage',
            name='section_2_content',
            field=wagtail.fields.StreamField([('rich_text', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
        migrations.AlterField(
            model_name='seolandingpage',
            name='section_3_content',
            field=wagtail.fields.StreamField([('rich_text', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
        migrations.AlterField(
            model_name='seolandingpage',
            name='section_4_content',
            field=wagtail.fields.StreamField([('rich_text', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
        migrations.AlterField(
            model_name='seolandingpage',
            name='section_5_content',
            field=wagtail.fields.StreamField([('rich_text', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
        migrations.AlterField(
            model_name='seolandingpage',
            name='selected_rehab_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of RehabCenter IDs e.g. [1, 2, 3]'),
        ),
        migrations.AlterField(
            model_name='treatmentlandingpage',
            name='about',
            field=wagtail.fields.StreamField([('rich_text', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
        migrations.AlterField(
            model_name='treatmentlandingpage',
            name='intro',
            field=wagtail.fields.StreamField([('rich_text', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
    ]
